### ISSUE TITLE
Know-how IP 

### ISSUE THREAD

**Issue by erinmr** [FAIRIslandProject/Generic-Place-based-Data-Policy#15]
https://github.com/FAIRIslandProject/Generic-Place-based-Data-Policy/blob/a3f0470f6fc439e801c462a2e02959dbb9559d3b/GenericPlacebasedDataPolicy.Rmd#L74

EK! Listing "know how" makes me uneasy. 

But I'm curious, why do participants have to list there IP? This really is coming from my ignorance...would listing it require different protections on that data? If not, then why does it need to be listed?

**Comment by erinmr** [comment]
I don't think this is how we are using the DMP. Curious what others think. We could strike this. The thing we want to know is about intended outputs covered in b.

**Comment by mariapraetzellis** [comment]
I'm interested to hear what Neil thinks about this question. I'm also not sure about including it in the DMP.

**Comment by erinmr** [comment]
change to: (e.g. patents, copyright, etc. )
