### ISSUE TITLE
Commercial combine with IP doesn't make sense in ethical/social section

### ISSUE THREAD

**Issue by erinmr** [FAIRIslandProject/Generic-Place-based-Data-Policy#16]
https://github.com/FAIRIslandProject/Generic-Place-based-Data-Policy/blob/a3f0470f6fc439e801c462a2e02959dbb9559d3b/GenericPlacebasedDataPolicy.Rmd#L76

Commerical could be hand-in-hand with IP, and I'm not sure it makes sense here in terms of ethical/social etc consequences.

**Comment by erinmr** [comment]
I think commercial does make sense here, but should be explicit instead of parenthetical. We could modify to -> "Describe potential ethical, legal, commercial or social consequences ...

**Comment by mariapraetzellis** [comment]
Being explicit here and removing it from the parens makes sense to me.

**Comment by erinmr** [comment]
Add as a separate bullet cut commercial out of d and create new d. - list potential commercial uses of intended outputs 

put right below intellectual property and ethics becomes e 

Remove period at the end of d
