### ISSUE TITLE
Is there a chance identifiers to risk to individual's privacy? 

### ISSUE THREAD

**Issue by erinmr** [FAIRIslandProject/Generic-Place-based-Data-Policy#17]
https://github.com/FAIRIslandProject/Generic-Place-based-Data-Policy/blob/a3f0470f6fc439e801c462a2e02959dbb9559d3b/GenericPlacebasedDataPolicy.Rmd#L82

What about the flip side of this, ensuring privacy protections? The more we link data and especially if identifiers are being used, the more of a chance there is to risk someone's privacy.

**Comment by mariapraetzellis** [comment]
I think we're okay here, though perhaps I'm misunderstanding. Since identifiers are for the PIs, their research outputs, and related metadata about the work (like the DMP-ID), not for the underlining data, I don't think there would be privacy concerns. We should discuss this as a group.

**Comment by erinmr** [comment]
Group agreed that identifiers do not carry a privacy risk in this instance.
