### ISSUE TITLE
Agreement or arrangement? 

### ISSUE THREAD

**Issue by erinmr** [FAIRIslandProject/Generic-Place-based-Data-Policy#18]
https://github.com/FAIRIslandProject/Generic-Place-based-Data-Policy/blob/a3f0470f6fc439e801c462a2e02959dbb9559d3b/GenericPlacebasedDataPolicy.Rmd#L84

an agreement or an arrangement?

**Comment by erinmr** [comment]
I think this should be arrangement. Other thoughts?

**Comment by mariapraetzellis** [comment]
Arrangement makes sense to me in this instance.

**Comment by erinmr** [comment]
Go for arrangement
