### ISSUE TITLE
 What about institutional policies? 

### ISSUE THREAD

**Issue by erinmr** [FAIRIslandProject/Generic-Place-based-Data-Policy#3]
https://github.com/FAIRIslandProject/Generic-Place-based-Data-Policy/blob/80783c9c67e2f7a8c7dd3cdee7e78949bdccb695/GenericPlacebasedDataPolicy.Rmd#L32

What about institutional policies? For example, what if one institution has policies restricting certain sensitive data? Would the inclusion of "and institutional policies" work here?

**Comment by erinmr** [comment]
Seems ok to also add institutional policies here.

**Comment by mariapraetzellis** [comment]
Yes, I agree with adding institutional policies here.

**Comment by erinmr** [comment]
Change to: This policy does not impose legally-binding conditions nor replace or impinge on legal obligations and/or institutional policies that might apply elsewhere.
