### ISSUE TITLE
Elsewhere

### ISSUE THREAD

**Issue by erinmr** [FAIRIslandProject/Generic-Place-based-Data-Policy#4]
https://github.com/FAIRIslandProject/Generic-Place-based-Data-Policy/blob/80783c9c67e2f7a8c7dd3cdee7e78949bdccb695/GenericPlacebasedDataPolicy.Rmd#L32

I suggest removing "elsewhere." To me it brings up what the extent of scope this policies applies. For example, would member institutions need to abide by China's new privacy policy when they are not engaged in research utilizing data restricted by that policy?

**Comment by mariapraetzellis** [comment]
What about:

> This policy does not impose legally-binding conditions nor replace or impinge on other related legal obligations that might apply.
