### ISSUE TITLE
Use of wise

### ISSUE THREAD

**Issue by erinmr** [FAIRIslandProject/Generic-Place-based-Data-Policy#5]
https://github.com/FAIRIslandProject/Generic-Place-based-Data-Policy/blob/80783c9c67e2f7a8c7dd3cdee7e78949bdccb695/GenericPlacebasedDataPolicy.Rmd#L36

I'm sorry, this may just be my ignorance but I'm getting hung up on the word "wise" here. How do we know when a wise decision was made, how do we measure it? 
Perhaps drawing upon the goal of this policy, it could be said that..."support decision-making that facilitates further research and equitable stewardship..." ?

**Comment by mariapraetzellis** [comment]
Equitable stewardship sounds good to me.

**Comment by erinmr** [comment]
From Neil: On “wise”:

This is aspirational and not everything needs to be measured (quantified). People know what it means in this context. It seems justified to me as it is setting the goals (it is in the articles of incorporation of Tetiaroa Society).
